# Generated by Django 5.2.6 on 2025-10-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itempedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo de PRODUÇÃO por unidade ou por metro quadrado', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(blank=True, default=0, help_text='Quantidade atual em estoque. Nulo para serviços.', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(blank=True, default=0, help_text='Nível de alerta para o estoque', null=True),
        ),
    ]
