# Generated by Django 5.2.6 on 2025-11-05 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_arte',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_APROVACAO', 'Em Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='ArtePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.ImageField(help_text='Arquivo de imagem da arte', upload_to='artes_pedidos/')),
                ('comentarios_admin', models.TextField(blank=True, help_text='Comentários/instruções do admin', null=True)),
                ('comentarios_cliente', models.TextField(blank=True, help_text='Comentários/revisões do cliente', null=True)),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artes', to='core.pedido')),
            ],
        ),
    ]
