# Generated by Django 5.2.6 on 2025-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_status_arte_artepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_aprovacao',
            field=models.UUIDField(blank=True, editable=False, help_text='Token único para a página de aprovação do cliente', null=True, unique=True),
        ),
    ]
