# Generated by Django 5.2.6 on 2025-11-06 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedido_token_aprovacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaPortaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('CONDOMINIO', 'Cliente Condomínio'), ('RETIRADA', 'Cliente Retirada')], default='CONDOMINIO', max_length=20)),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Responsável pela Retirada')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloco', models.CharField(blank=True, max_length=100, null=True)),
                ('apartamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Portaria',
                'verbose_name_plural': 'Etiquetas de Portaria',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
