# Generated by Django 5.2.6 on 2025-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
