# Generated by Django 5.2.6 on 2025-11-06 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orcamento_valor_desconto_orcamento_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_validade',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
