# Generated by Django 5.2.6 on 2025-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orcamento_data_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Data de validade da proposta', null=True),
        ),
    ]
