# Generated by Django 5.2.6 on 2025-11-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_orcamento_data_validade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('contato_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('servicos_prestados', models.TextField(blank=True, help_text='Serviços principais (ex: Impressão Lona, Corte, Acrílico)', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='link_fornecedor',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='custo_producao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo total de fornecedores (calculado por signal)', max_digits=10),
        ),
        migrations.CreateModel(
            name='CustoFornecedorPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do serviço/produto (ex: Impressão Lona)', max_length=255)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_fornecedores', to='core.pedido')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Custo de Fornecedor',
                'verbose_name_plural': 'Custos de Fornecedores',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
