# Generated by Django 5.2.6 on 2025-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fornecedor_remove_pedido_link_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
