# Generated by Django 5.2.6 on 2025-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacoes_producao',
            field=models.TextField(blank=True, help_text='Observações internas para a produção (ex: sangria, cor especial)', null=True),
        ),
    ]
