# Generated by Django 5.2.6 on 2025-11-07 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itempedido_observacoes_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Positivo para entradas, Negativo para saídas')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada (Compra)'), ('ENTRADA_AJUSTE', 'Entrada (Ajuste Manual)'), ('SAIDA_AJUSTE', 'Saída (Ajuste Manual/Perda)')], default='ENTRADA_COMPRA', max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Nota Fiscal 123, Ajuste de inventário', null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
