# Generated by Django 5.2.6 on 2025-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['data'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AddField(
            model_name='custofornecedorpedido',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que o custo foi efetivamente pago', null=True),
        ),
        migrations.AddField(
            model_name='custofornecedorpedido',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento para pagamento ao fornecedor', null=True),
        ),
        migrations.AddField(
            model_name='custofornecedorpedido',
            name='status',
            field=models.CharField(choices=[('A PAGAR', 'A Pagar'), ('PAGO', 'Pago')], default='A PAGAR', max_length=10),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que a despesa foi efetivamente paga', null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('A PAGAR', 'A Pagar'), ('PAGO', 'Pago')], default='A PAGAR', max_length=10),
        ),
    ]
